title: Notes for Philosophy of Sciences (2019 Autumn)
description: MOOC on Xuetangx, taught by Shanxi University
show_downloads: false
google_analytics: true
theme: jekyll-theme-cayman
mathjax: true
markdown: kramdown
